variable "GOOGLE_CLOUD_PROJECT_NAME" { }
variable "GOOGLE_CLOUD_PROJECT_ID" { }
variable "GOOGLE_CLOUD_REGION" { }
variable "GOOGLE_CLOUD_BUCKET_REGION" { }
variable "GOOGLE_CLOUD_SOURCE_BUCKET_NAME" { }
variable "MODULE_IMG_THUMB_GEN_SOURCE_PATH" {}
variable "MODULE_IMG_THUMB_GEN_SOURCE_BUCKET_NAME" { }
