variable "GOOGLE_CLOUD_PROJECT_NAME" { }
variable "GOOGLE_CLOUD_REGION" { }
variable "MODULE_DB_POSTGRES_DB_NAME" { }
variable "MODULE_DB_POSTGRES_INSTANCE_NAME" { }
variable "MODULE_DB_POSTGRES_DB_STAGE_NAME" { }

